const $=id=>document.getElementById(id),v=$('video'),c=$('canvas'),ctx=c.getContext('2d');
let url=null,bitmap=null,points=Array(6).fill(null),records=[],model=null,busy=false,frameTime=0,generation=0;
const say=t=>$('status').textContent=t;
function clearFrame(){points=Array(6).fill(null);bitmap=null;$('verified').checked=false;$('canvas').hidden=true;$('editor').hidden=true;$('analyze').disabled=true;}
function clearAll(){generation++;if(url)URL.revokeObjectURL(url);url=null;v.removeAttribute('src');v.load();v.hidden=true;$('empty').hidden=false;$('file').value='';$('filename').textContent='No video selected';$('capture').disabled=true;clearFrame();records=[];render();say('Play or scrub to a fully extended position, then capture it.');}
$('clear').onclick=clearAll;
$('file').onchange=()=>{const f=$('file').files[0];if(!f)return;if(!$('consent').checked){$('file').value='';say('Please confirm permission before choosing a video.');return;}if(f.size>200*1024*1024){$('file').value='';say('Choose a video smaller than 200 MB.');return;}generation++;if(url)URL.revokeObjectURL(url);records=[];render();clearFrame();url=URL.createObjectURL(f);v.src=url;v.hidden=false;$('empty').hidden=true;$('filename').textContent=f.name;$('capture').disabled=true;say('Loading video…');};
v.onloadedmetadata=()=>{$('capture').disabled=false;say('Scrub to a clear, extended-leg checkpoint. Capture several nearby frames for a stability review.');};
v.onerror=()=>say('This browser could not decode the video. Try an H.264 MP4 export.');
v.ontimeupdate=()=>$('time').textContent=`${v.currentTime.toFixed(2)} s`;
$('consent').onchange=()=>{if(!$('consent').checked&&url)clearAll();};
$('capture').onclick=()=>{if(!v.videoWidth||busy)return;v.pause();c.width=Math.min(v.videoWidth,1280);c.height=Math.round(c.width*v.videoHeight/v.videoWidth);ctx.drawImage(v,0,0,c.width,c.height);bitmap=ctx.getImageData(0,0,c.width,c.height);points=Array(6).fill(null);frameTime=v.currentTime;$('verified').checked=false;c.hidden=false;$('editor').hidden=false;$('analyze').disabled=false;$('point').value='0';say('Mark the waterline and visible leg, or ask AI to suggest the leg points.');};
function draw(){if(!bitmap)return;ctx.putImageData(bitmap,0,0);ctx.lineWidth=3;[[0,1],[2,3],[3,4],[4,5]].forEach(([a,b])=>{if(points[a]&&points[b]){ctx.strokeStyle=a===0?'#ffe48e':'#4bf6d4';ctx.beginPath();ctx.moveTo(...points[a]);ctx.lineTo(...points[b]);ctx.stroke();}});points.forEach((p,i)=>{if(!p)return;ctx.fillStyle=i<2?'#ffe48e':'#4bf6d4';ctx.beginPath();ctx.arc(p[0],p[1],6,0,Math.PI*2);ctx.fill();ctx.font='bold 17px sans-serif';ctx.strokeStyle='#0b202e';ctx.lineWidth=4;ctx.strokeText(String(i+1),p[0]+10,p[1]-8);ctx.fillText(String(i+1),p[0]+10,p[1]-8);});}
function setPoint(x,y){if(!bitmap||busy)return;const i=Number($('point').value);points[i]=[x,y];$('verified').checked=false;$('point').value=String(Math.min(5,i+1));draw();}
c.onclick=e=>{const b=c.getBoundingClientRect();setPoint((e.clientX-b.left)*c.width/b.width,(e.clientY-b.top)*c.height/b.height);};
$('setpoint').onclick=()=>{const x=Number($('px').value),y=Number($('py').value);if($('px').value===''||$('py').value===''||x<0||x>100||y<0||y>100){say('Enter X and Y between 0 and 100.');return;}setPoint(x*c.width/100,y*c.height/100);};
$('reset').onclick=()=>{if(busy)return;points=Array(6).fill(null);$('verified').checked=false;draw();};
$('analyze').onclick=async()=>{if(!bitmap||busy)return;busy=true;const gen=generation;$('analyze').disabled=true;$('capture').disabled=true;say('Loading the pose model and estimating landmarks. The first run may take a moment…');try{if(!model){const {PoseLandmarker,FilesetResolver}=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/vision_bundle.mjs');const fs=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');model=await PoseLandmarker.createFromOptions(fs,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task'},runningMode:'IMAGE',numPoses:1,minPoseDetectionConfidence:0.5,minPosePresenceConfidence:0.5});}if(gen!==generation||!bitmap)return;ctx.putImageData(bitmap,0,0);const result=model.detect(c);const lm=result.landmarks?.[0];if(!lm){draw();say('AI could not locate a reliable pose. Mark the visible points manually; no measurements were invented.');return;}const legs=[[23,25,27,31],[24,26,28,32]];const score=ids=>ids.reduce((s,i)=>s+(lm[i]?.visibility||0),0);legs.sort((a,b)=>score(b)-score(a));const leg=legs[0];leg.forEach((id,i)=>{const p=lm[id];points[i+2]=p&&p.visibility>=.7&&p.x>=0&&p.x<=1&&p.y>=0&&p.y<=1?[p.x*c.width,p.y*c.height]:null;});$('verified').checked=false;draw();say('AI suggestions only: verify the intended extended leg, remove hidden points with Reset, and mark the waterline. Confidence is not proof of visibility.');}catch(e){draw();say('AI model could not load or run in this browser. Manual landmark analysis remains available.');}finally{busy=false;$('analyze').disabled=!bitmap;$('capture').disabled=!url;}};
const dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
function calculate(p){if(!p[0]||!p[1]||!p[3]||!p[4])throw Error('Mark both waterline points, knee and ankle. Leave hidden points unmarked.');const w=dist(p[0],p[1]),s=dist(p[3],p[4]);if(w<20||s<15)throw Error('Waterline and shin points are too close for a useful measurement.');let n=[(p[1][1]-p[0][1])/w,-(p[1][0]-p[0][0])/w];if(n[1]>0)n=n.map(x=>-x);const leg=[p[4][0]-p[3][0],p[4][1]-p[3][1]];const angle=Math.acos(Math.min(1,Math.abs((leg[0]*n[0]+leg[1]*n[1])/s)))*180/Math.PI;const clearance=((p[4][0]-p[0][0])*n[0]+(p[4][1]-p[0][1])*n[1])/s;let extension=null;if(p[2]&&dist(p[2],p[3])>15){const a=[p[2][0]-p[3][0],p[2][1]-p[3][1]],b=leg;extension=Math.acos(Math.max(-1,Math.min(1,(a[0]*b[0]+a[1]*b[1])/(Math.hypot(...a)*s))))*180/Math.PI;}return {angle,extension,clearance};}
$('save').onclick=()=>{if(busy)return;if(!$('verified').checked){say('Verify visible landmarks first.');return;}try{const m=calculate(points);if(records.some(r=>Math.abs(r.time-frameTime)<.01)){say('This frame is already saved. Capture a different time.');return;}records.push({...m,time:frameTime,group:$('group').value,figure:$('figure').value,phase:$('phase').value.trim()||'Checkpoint',image:c.toDataURL('image/jpeg',.65),points:points.map(p=>p?p.slice():null),width:c.width,height:c.height});render();say('Key frame saved. Capture another frame in the same held position to compare.');}catch(e){say(e.message);}};
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
function render(){const ms=$('metrics'),fs=$('frames'),rs=$('recommendations');ms.replaceChildren();fs.replaceChildren();rs.replaceChildren();$('export').disabled=!records.length;if(!records.length){ms.append(el('p','Capture and verify a frame to see real measurements. No sample scores are shown.','muted'));fs.append(el('p','No frames saved yet.'));return;}const r=records.at(-1);const same=records.filter(x=>x.figure===r.figure&&x.phase===r.phase&&x.group===r.group);const span=Math.max(...same.map(x=>x.time))-Math.min(...same.map(x=>x.time));const stable=same.length>=3&&span>=.5&&span<=3;const range=stable?Math.max(...same.map(x=>x.angle))-Math.min(...same.map(x=>x.angle)):null;[['Shin tilt',r.angle.toFixed(1)+'°','From waterline normal'],['Knee extension',r.extension===null?'Not visible':r.extension.toFixed(1)+'°','180° = straight in this view'],['Ankle clearance',r.clearance.toFixed(2)+'×','Relative to visible shin length'],['Sampled tilt range',stable?range.toFixed(1)+'°':'Need 3 frames','Same held checkpoint · 0.5–3 s']].forEach(([a,b,d])=>{const box=el('div',undefined,'metric');box.append(el('span',a),el('strong',b),el('small',d));ms.append(box);});
const advice=[];if(r.angle>5)advice.push(['Alignment to review',`Visible shin tilt is ${r.angle.toFixed(1)}°. Compare the overlay with the required position; ask your coach to check whether this is technique or camera perspective. A coach-supervised dry-land alignment rehearsal may help.`]);else advice.push(['Alignment observation',`Visible shin tilt is ${r.angle.toFixed(1)}°. This describes one projected segment, not full-body correctness.`]);if(r.extension!==null&&r.extension<170)advice.push(['Extension to review',`The projected knee angle is ${r.extension.toFixed(1)}°. Review a slow, comfortable dry-land leg extension with your coach, keeping the knee straight without forcing it.`]);else if(r.extension===null)advice.push(['Extension cannot be assessed','The hip is not marked as visible. Do not infer knee extension from the shin alone.']);advice.push(['Height: compare, do not grade',`Ankle clearance is ${r.clearance.toFixed(2)} shin lengths. Compare only matched camera views and the same phase; this is not an official height score or a body-strength diagnosis.`]);if(stable)advice.push(['Stability observation',`Across ${same.length} frames spanning ${span.toFixed(2)} s, shin tilt changed by ${range.toFixed(1)}°. Ask your coach whether that motion is intended. Hand placement and camera movement can also change the result.`]);advice.push(['Practice resources',r.figure==='Ballet leg'?'Use the linked Swim England ballet-leg demonstrations below to review extension and the raised-leg position with your coach.':'Use the official figure-review sheets below for this checkpoint. The linked ballet-leg videos are not drills for every figure.']);advice.forEach(([title,t])=>{const b=el('div',undefined,'recommendation');b.append(el('h3',title),el('p',t));rs.append(b);});rs.append(el('p','Review triggers of 5° tilt and 170° knee angle are provisional app heuristics, not official deductions or validated cutoffs. Recommendations are rule-based, not generated diagnoses.','muted'));
records.forEach((x,i)=>{const box=el('div',undefined,'frame'),im=el('img');im.src=x.image;im.alt=`Annotated ${x.phase} at ${x.time.toFixed(2)} seconds`;const del=el('button','Remove','secondary');del.onclick=()=>{records.splice(i,1);render();};box.append(im,el('p',`${x.phase} · ${x.time.toFixed(2)} s`),el('small',`${x.group} · ${x.figure}`),del);fs.append(box);});}
$('export').onclick=()=>{const data={app:'FigureSense MVP',reference:'2022–2025 manual; current competition eligibility unverified',method:'Human-verified 2D landmarks; optional MediaPipe suggestions; no official scoring',records:records.map(({image,...r})=>r)};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=u;a.download='figuresense-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
