const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const source = fs.readFileSync(path.join(__dirname, '..', 'app.js'), 'utf8');
const start = source.indexOf('const dist=');
const end = source.indexOf("$('save').onclick");
assert(start >= 0 && end > start, 'Calculation block not found; update test extraction after refactoring.');
const calculate = new Function(source.slice(start, end) + ';return calculate;')();
const near = (a, b) => assert(Math.abs(a - b) < 1e-6, `${a} != ${b}`);
const straight = [[0, 100], [200, 100], [100, 80], [100, 50], [100, 20], null];
const r = calculate(straight);
near(r.angle, 0); near(r.extension, 180); near(r.clearance, 80 / 30);
const noHip = straight.map(p => p && [...p]); noHip[2] = null;
assert.equal(calculate(noHip).extension, null);
const reversed = [...straight]; reversed[0] = straight[1]; reversed[1] = straight[0];
near(calculate(reversed).clearance, r.clearance);
const bent = straight.map(p => p && [...p]); bent[2] = [70, 50];
near(calculate(bent).extension, 90);
assert.throws(() => calculate(Array(6).fill(null)));
console.log('PASS: verticality, knee extension, missing hip, reversed waterline, and missing-point guard.');
